### ISSUE TITLE
PHP Fatal error:  Call to undefined method PHPUnit_Framework_TestResult::allCompletlyImplemented()

### ISSUE THREAD

**Issue by isidromerayo** [Maher4Ever/guard-phpunit#10]
I have upgrade PHPUnit

```
# phpunit --version
PHPUnit 3.7.14 by Sebastian Bergmann.
```

The problem :(
  09:11:48 - INFO - Running all tests
  PHP Fatal error:  Call to undefined method PHPUnit_Framework_TestResult::allCompletlyImplemented() in    /var/lib/gems/1.9.1/gems/guard-phpunit-0.1.4/lib/guard/phpunit/formatters/PHPUnit-  Progress/PHPUnit/Extensions/Progress/ResultPrinter.php on line 250
  PHP Stack trace:
  PHP   1. {main}() /usr/bin/phpunit:0
  PHP   2. PHPUnit_TextUI_Command::main($exit = _uninitialized_) /usr/bin/phpunit:46
  PHP   3. PHPUnit_TextUI_Command->run($argv = array (0 => '/usr/bin/phpunit', 1 => '--include-path', 2 => '/var/lib/gems/1.9.1/gems/guard-phpunit-0.1.4/lib/guard/phpunit/formatters/PHPUnit-Progress', 3 => '--printer', 4 => 'PHPUnit_Extensions_Progress_ResultPrinter', 5 => '-c', 6 => 'app/phpunit.xml.dist', 7 => 'src'), $exit = TRUE) /usr/share/php/PHPUnit/TextUI/Command.php:129
  PHP   4. PHPUnit_TextUI_TestRunner->doRun($suite = class PHPUnit_Framework_TestSuite { protected $backupGlobals = FALSE; protected $backupStaticAttributes = NULL; protected $name = 'src'; protected $groups = array ('imerayo' => array (...)); protected $tests = array (0 => class PHPUnit_Framework_TestSuite { ... }, 1 => class PHPUnit_Framework_TestSuite { ... }, 2 => class PHPUnit_Framework_TestSuite { ... }, 3 => class PHPUnit_Framework_TestSuite { ... }, 4 => class PHPUnit_Framework_TestSuite { ... }, 5 => class PHPUnit_Framework_TestSuite { ... }); protected $numTests = 13; protected $testCase = FALSE }, $arguments = array ('listGroups' => FALSE, 'loader' => NULL, 'useDefaultConfiguration' => TRUE, 'printer' => class PHPUnit_Extensions_Progress_ResultPrinter { protected $column = 13; protected $maxColumn = 65; protected $lastTestFailed = FALSE; protected $numAssertions = 30; protected $numTests = 13; protected $numTestsRun = 13; protected $numTestsWidth = 2; protected $colors = FALSE; protected $debug = FALSE; protected $verbose = FALSE; protected $autoFlush = FALSE; protected $out = NULL; protected $outTarget = NULL; protected $printsHTML = FALSE }, 'configuration' => 'app/phpunit.xml.dist', 'testSuffixes' => array (0 => 'Test.php', 1 => '.phpt'))) /usr/share/php/PHPUnit/TextUI/Command.php:176
  PHP   5. PHPUnit_Extensions_Progress_ResultPrinter->printResult($result = class PHPUnit_Framework_TestResult { protected $passed = array ('Hcuv\BlogBundle\Tests\Controller\BlogControllerTest::showBlogWithInvalidIdError404' => array (...), 'Hcuv\BlogBundle\Tests\Controller\BlogControllerTest::showBlogWithPreviousCreate' => array (...), 'Hcuv\BlogBundle\Tests\Controller\PageControllerTest::shouldBeShowInitialBlogHomePage' => array (...), 'Hcuv\BlogBundle\Tests\Controller\PageControllerTest::shouldBeGenerateHTTPError405MethodNoAllowedInBlogHomePageUsingMethodPost' => array (...), 'Hcuv\BlogBundle\Tests\Controller\PageControllerTest::shouldBeShowAboutPage' => array (...), 'Hcuv\BlogBundle\Tests\Controller\PageControllerTest::shouldBeShowContactFormPage' => array (...), 'Hcuv\BlogBundle\Tests\Controller\PageControllerTest::shouldBeProcessContactForm' => array (...), 'Hcuv\BlogBundle\Tests\Entity\BlogTest::createBlogWithEmptyComments' => array (...), 'Hcuv\BlogBundle\Tests\Entity\EnquiryTest::shouldBeCreateEnquiry' => array (...), 'Hcuv\BlogBundle\Tests\Entity\EnquiryTest::shouldBeSettersValuesEqualsGettersEnquiry' => array (...), 'Hcuv\BlogBundle\Tests\Form\EnquiryTypeTest::createForm' => array (...), 'Hcuv\BlogBundle\Tests\Repository\BlogRepositoryTest::getLatestBlogsWithoutLimit' => array (...), 'Hcuv\BlogBundle\Tests\Repository\BlogRepositoryTest::getLatestBlogsWithLimit2' => array (...)); protected $errors = array (); protected $deprecatedFeatures = array (); protected $failures = array (); protected $notImplemented = array (); protected $skipped = array (); protected $listeners = array (0 => class PHPUnit_Extensions_Progress_ResultPrinter { ... }, 1 => class PHPUnit_Util_DeprecatedFeature_Logger { ... }); protected $runTests = 13; protected $time = 1.6750390529633; protected $topTestSuite = class PHPUnit_Framework_TestSuite { protected $backupGlobals = FALSE; protected $backupStaticAttributes = NULL; protected $name = 'src'; protected $groups = array (...); protected $tests = array (...); protected $numTests = 13; protected $testCase = FALSE }; protected $codeCoverage = NULL; protected $convertErrorsToExceptions = TRUE; protected $stop = FALSE; protected $stopOnError = FALSE; protected $stopOnFailure = FALSE; protected $strictMode = FALSE; protected $stopOnIncomplete = FALSE; protected $stopOnSkipped = FALSE; protected $lastTestFailed = FALSE; protected $timeoutForSmallTests = 1; protected $timeoutForMediumTests = 10; protected $timeoutForLargeTests = 60 }) /usr/share/php/PHPUnit/TextUI/TestRunner.php:352
    PHP   6. PHPUnit_Extensions_Progress_ResultPrinter->printFooter($result = class PHPUnit_Framework_TestResult { protected $passed = array ('Hcuv\BlogBundle\Tests\Controller\BlogControllerTest::showBlogWithInvalidIdError404' => array (...), 'Hcuv\BlogBundle\Tests\Controller\BlogControllerTest::showBlogWithPreviousCreate' => array (...), 'Hcuv\BlogBundle\Tests\Controller\PageControllerTest::shouldBeShowInitialBlogHomePage' => array (...), 'Hcuv\BlogBundle\Tests\Controller\PageControllerTest::shouldBeGenerateHTTPError405MethodNoAllowedInBlogHomePageUsingMethodPost' => array (...), 'Hcuv\BlogBundle\Tests\Controller\PageControllerTest::shouldBeShowAboutPage' => array (...), 'Hcuv\BlogBundle\Tests\Controller\PageControllerTest::shouldBeShowContactFormPage' => array (...), 'Hcuv\BlogBundle\Tests\Controller\PageControllerTest::shouldBeProcessContactForm' => array (...), 'Hcuv\BlogBundle\Tests\Entity\BlogTest::createBlogWithEmptyComments' => array (...), 'Hcuv\BlogBundle\Tests\Entity\EnquiryTest::shouldBeCreateEnquiry' => array (...), 'Hcuv\BlogBundle\Tests\Entity\EnquiryTest::shouldBeSettersValuesEqualsGettersEnquiry' => array (...), 'Hcuv\BlogBundle\Tests\Form\EnquiryTypeTest::createForm' => array (...), 'Hcuv\BlogBundle\Tests\Repository\BlogRepositoryTest::getLatestBlogsWithoutLimit' => array (...), 'Hcuv\BlogBundle\Tests\Repository\BlogRepositoryTest::getLatestBlogsWithLimit2' => array (...)); protected $errors = array (); protected $deprecatedFeatures = array (); protected $failures = array (); protected $notImplemented = array (); protected $skipped = array (); protected $listeners = array (0 => class PHPUnit_Extensions_Progress_ResultPrinter { ... }, 1 => class PHPUnit_Util_DeprecatedFeature_Logger { ... }); protected $runTests = 13; protected $time = 1.6750390529633; protected $topTestSuite = class PHPUnit_Framework_TestSuite { protected $backupGlobals = FALSE; protected $backupStaticAttributes = NULL; protected $name = 'src'; protected $groups = array (...); protected $tests = array (...); protected $numTests = 13; protected $testCase = FALSE }; protected $codeCoverage = NULL; protected $convertErrorsToExceptions = TRUE; protected $stop = FALSE; protected $stopOnError = FALSE; protected $stopOnFailure = FALSE; protected $strictMode = FALSE; protected $stopOnIncomplete = FALSE; protected $stopOnSkipped = FALSE; protected $lastTestFailed = FALSE; protected $timeoutForSmallTests = 1; protected $timeoutForMediumTests = 10; protected $timeoutForLargeTests = 60 }) /var/lib/gems/1.9.1/gems/guard-phpunit-0.1.4/lib/guard/phpunit/formatters/PHPUnit-  Progress/PHPUnit/Extensions/Progress/ResultPrinter.php:72
  09:11:50 - INFO - .............

> [#CD7BDA6FF975] 
> [#CD7BDA6FF975] Finished in 1 second

Thanks

**Comment by neerolyte** [comment]
This is due to: https://github.com/Maher4Ever/phpunit-progress/issues/1

**Comment by mikedfunk** [comment]
I am still getting this error. I have phpunit version 3.7.19. I have updated all my ruby gems and pear packages. How do I fix it?

**Comment by paolooo** [comment]
Got the same error:

``` PHP
Fatal error: Call to undefined method PHPUnit_Framework_TestResult::allCompletlyImplemented() in C:\RailsInstaller\Ruby1.9.3\lib\ruby\gems\1.9.1\gems\guard-phpunit-0.1.4\lib\guard\phpunit\formatters\PHPUnit-Progress\PHPUnit\Extensions\Progress\ResultPrinter.php on line 250
```

To fix this issue, edit `ResultPrinter.php`. In my case, it's in

```
C:\RailsInstaller\Ruby1.9.3\lib\ruby\gems\1.9.1\gems\guard-phpunit-0.1.4\lib\guard\phpunit\formatters\PHPUnit-Progress\PHPUnit\Extensions\Progress\ResultPrinter.php
```

on line 250 and 256 and edit `$result->allCompletlyImplemented()` to `$result->allCompletelyImplemented()`

**Comment by tshafer** [comment]
using paolooo comments fixed it for me.

**Comment by ikhsan017** [comment]
+1 for paolooo, it also fix the error on my side

**Comment by rawaludin** [comment]
+1 for @paolooo fix for me too.. :+1:

**Comment by WMeldon** [comment]
I'm commenting to remember this....and +1 to @paolooo

**Comment by alnutile** [comment]
+1 for @paolooo fix for me too..

**Comment by s-mizushima** [comment]
fix for me too thanx! @paolooo

**Comment by abtris** [comment]
+1

**Comment by EdRands** [comment]
Thank you, @paolooo.

**Comment by sgerrand** [comment]
The problem is actually in another repository: [Maher4Ever/phpunit-progress](https://github.com/Maher4Ever/phpunit-progress), and is specifically fixed by [Mayer4Ever/phpunit-progress#2](https://github.com/Maher4Ever/phpunit-progress/issues/2).

Please merge this change for Great Good. :wave:

**Comment by mboughaba** [comment]
fix for me too thanx! @paolooo

**Comment by grbritz** [comment]
Thank you! @paolooo

**Comment by chisumo2016** [comment]
C:\xampp\htdocs\magazine-blog3>composer info phpunit/phpunit
name     : phpunit/phpunit
descrip. : The PHP Unit Testing framework.
keywords : phpunit, testing, xunit
versions : * 5.7.9
type     : library
license  : BSD 3-clause "New" or "Revised" License (BSD-3-Clause) (OSI approved) https://spdx.org/licenses/BSD-3-Clause.html#licenseText
source   : [git] https://github.com/sebastianbergmann/phpunit.git 69f832b87c731d5cacad7f91948778fe98335fdd
dist     : [zip] https://api.github.com/repos/sebastianbergmann/phpunit/zipball/69f832b87c731d5cacad7f91948778fe98335fdd 69f832b87c731d5cacad7f91948778fe98335fdd
names    : phpunit/phpunit

autoload
classmap
src/

requires
ext-dom *
ext-json *
ext-libxml *
ext-mbstring *
ext-xml *
myclabs/deep-copy ~1.3
php ^5.6 || ^7.0
phpspec/prophecy ^1.6.2
phpunit/php-code-coverage ^4.0.4
phpunit/php-file-iterator ~1.4
phpunit/php-text-template ~1.2
phpunit/php-timer ^1.0.6
phpunit/phpunit-mock-objects ^3.2
sebastian/comparator ~1.2.2
sebastian/diff ~1.2
sebastian/environment ^1.3.4 || ^2.0
sebastian/exporter ~2.0
sebastian/global-state ^1.0 || ^2.0
sebastian/object-enumerator ~2.0
sebastian/resource-operations ~1.0
sebastian/version ~1.0|~2.0
symfony/yaml ~2.1|~3.0


C:\xampp\htdocs\magazine-blog3>composer global update
Changed current directory to C:/Users/bundalla/AppData/Roaming/Composer
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files

C:\xampp\htdocs\magazine-blog3>phpunit
PHP Fatal error:  Uncaught Error: Call to undefined method PHPUnit_Util_Configuration::getTestdoxGroupConfiguration() in C:\xampp\htdocs\magazine-blog3\vendor\phpunit\phpunit\src\TextUI\TestRunner.php:1046
Stack trace:
#0 C:\xampp\htdocs\magazine-blog3\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(167): PHPUnit_TextUI_TestRunner->handleConfiguration(Array)
#1 C:\xampp\php\pear\PHPUnit\TextUI\Command.php(176): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#2 C:\xampp\php\pear\PHPUnit\TextUI\Command.php(129): PHPUnit_TextUI_Command->run(Array, true)
#3 C:\xampp\php\phpunit(46): PHPUnit_TextUI_Command::main()
#4 {main}
  thrown in C:\xampp\htdocs\magazine-blog3\vendor\phpunit\phpunit\src\TextUI\TestRunner.php on line 1046

Fatal error: Uncaught Error: Call to undefined method PHPUnit_Util_Configuration::getTestdoxGroupConfiguration() in C:\xampp\htdocs\magazine-blog3\vendor\phpunit\phpunit\src\TextUI\TestRunner.php:1046
Stack trace:
#0 C:\xampp\htdocs\magazine-blog3\vendor\phpunit\phpunit\src\TextUI\TestRunner.php(167): PHPUnit_TextUI_TestRunner->handleConfiguration(Array)
#1 C:\xampp\php\pear\PHPUnit\TextUI\Command.php(176): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array)
#2 C:\xampp\php\pear\PHPUnit\TextUI\Command.php(129): PHPUnit_TextUI_Command->run(Array, true)
#3 C:\xampp\php\phpunit(46): PHPUnit_TextUI_Command::main()
#4 {main}
  thrown in C:\xampp\htdocs\magazine-blog3\vendor\phpunit\phpunit\src\TextUI\TestRunner.php on line 1046
